import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import { QuizContextProvider } from '@/context/quiz-context'

const font = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main className="bg-blur bg-darkNavy bg-cover bg-no-repeat min-h-screen">
          <QuizContextProvider>
            <div className="mx-auto max-w-7xl pb-12">{children}</div>
          </QuizContextProvider>
        </main>
      </body>
    </html>
  )
}
